version: 2.1
orbs:
  slack: circleci/slack@4.6.1
jobs:

  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          name: build and test
          working_directory: .
          command: ./scripts/ci_run.sh
      - store_artifacts:
          path: /artifacts/linux-x64.tgz
      - store_artifacts:
          path: /artifacts/osx-x64.tgz
      - store_artifacts:
          path: /artifacts/win-x64.tgz
      - store_artifacts:
          path: /artifacts/win-x86.tgz
      - slack/notify:
          event: fail
          template: basic_fail_1

  request-approval:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - slack/notify:
          event: pass
          template: basic_on_hold_1

  publish:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          name: run release script
          working_directory: .
          command: ./scripts/release.sh
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

workflows:

  build pull requests:
    jobs:
      - build:
          filters:
            branches:
              only:
                - /pull\/\d+/

  build dev branches:
    jobs:
      - build:
          filters:
            branches:
              only:
                - /dev\/\d+/

  build and publish tags:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
      - request-approval:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
      - wait_for_approval:
          type: approval
          requires:
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
      - publish:
          requires:
            - wait_for_approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
